[project]
name = "kineticconstructs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
<<<<<<< HEAD
    "python-dotenv>=1.1.0",
    "langflow >= 1.4.0",
=======
    "astrapy>=2.0.1",
    "openai>=1.70.0",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "langflow >= 1.3.4",
>>>>>>> 6afa79b88362dd6d462a46ab141448ff9c13bae4
]
